### ISSUE TITLE
can't install : code 7 path /home/$USER/FirmataGUI/node_modules/serialport command failed

### ISSUE THREAD

**Issue by krodelabestiole** [shengzhao91/FirmataGUI#2]
I have tried different versions of npm on my raspberry, thanks to nvm, but still the same error :

```
kro@pi:~/FirmataGUI $ npm install
npm WARN deprecated static-favicon@1.0.2: use serve-favicon module
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated constantinople@2.0.1: Please update to at least constantinople 3.1.1
npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated mkdirp@0.3.5: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated jade@1.3.1: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm ERR! code 7
npm ERR! path /home/kro/FirmataGUI/node_modules/serialport
npm ERR! command failed
npm ERR! command sh -c -- node-pre-gyp install --fallback-to-build
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.6.7
npm ERR! node-pre-gyp info using node@16.20.2 | linux | arm
npm ERR! node-pre-gyp info check checked for "/home/kro/FirmataGUI/node_modules/serialport/build/serialport/v1.7.3/Release/node-v93-linux-arm/serialport.node" (not found)
npm ERR! node-pre-gyp http GET https://node-serialport.s3.amazonaws.com/serialport/v1.7.3/Release/node-v93-linux-arm.tar.gz
npm ERR! node-pre-gyp ERR! UNCAUGHT EXCEPTION 
npm ERR! node-pre-gyp ERR! stack ReferenceError: primordials is not defined
npm ERR! node-pre-gyp ERR! stack     at evalmachine.<anonymous>:42:5
npm ERR! node-pre-gyp ERR! stack     at Object.<anonymous> (/home/kro/FirmataGUI/node_modules/serialport/node_modules/node-pre-gyp/node_modules/tar/node_modules/fstream/node_modules/graceful-fs/fs.js:11:1)
npm ERR! node-pre-gyp ERR! stack     at Module._compile (node:internal/modules/cjs/loader:1198:14)
npm ERR! node-pre-gyp ERR! stack     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
npm ERR! node-pre-gyp ERR! stack     at Module.load (node:internal/modules/cjs/loader:1076:32)
npm ERR! node-pre-gyp ERR! stack     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
npm ERR! node-pre-gyp ERR! stack     at Module.require (node:internal/modules/cjs/loader:1100:19)
npm ERR! node-pre-gyp ERR! stack     at require (node:internal/modules/cjs/helpers:119:18)
npm ERR! node-pre-gyp ERR! stack     at Object.<anonymous> (/home/kro/FirmataGUI/node_modules/serialport/node_modules/node-pre-gyp/node_modules/tar/node_modules/fstream/node_modules/graceful-fs/graceful-fs.js:3:27)
npm ERR! node-pre-gyp ERR! stack     at Module._compile (node:internal/modules/cjs/loader:1198:14)
npm ERR! node-pre-gyp ERR! System Linux 6.1.21-v7+
npm ERR! node-pre-gyp ERR! command "/home/kro/.nvm/versions/node/v16.20.2/bin/node" "/home/kro/FirmataGUI/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /home/kro/FirmataGUI/node_modules/serialport
npm ERR! node-pre-gyp ERR! node -v v16.20.2
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.6.7
npm ERR! node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
npm ERR! node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
npm ERR! node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kro/.npm/_logs/2024-02-29T15_24_49_076Z-debug-0.log
```

**Comment by shengzhao91** [comment]
This project has been 10 years old and no longer supported. Thank you for the interest.

**Comment by krodelabestiole** [comment]
ok I've updated `"serialport": "^1.4.0",` to `"serialport": "^12",` in `package.json` and I could install it.

thanks for your answer anyway.

if you know about any maintained software to control a firmata microcontroller from a web page I'm listening thought : strangely enough I could not find any.
I guess I would build something myself.

**Comment by shengzhao91** [comment]
Maybe look at the main page of Firmata. https://github.com/firmata/arduino
